### ISSUE TITLE
pychd not working

### ISSUE THREAD

**Issue by kukas** [diohabara/pychd#2]
Hey,

I tried to install this tool but running it yields the following error:
```
$ pychd
Traceback (most recent call last):
  File "/home/jirka/miniconda3/envs/deepcompyle310/bin/pychd", line 5, in <module>
    from src.pychd.main import cli
  File "/home/jirka/miniconda3/envs/deepcompyle310/lib/python3.10/site-packages/src/pychd/main.py", line 6, in <module>
    from . import compile, decompile
  File "/home/jirka/miniconda3/envs/deepcompyle310/lib/python3.10/site-packages/src/pychd/decompile.py", line 11, in <module>
    from pytype.pyc.magic import magic_word_to_version
ModuleNotFoundError: No module named 'pytype.pyc.magic'
```

the same error happens for `pychd decompile my_file.pyc` as well.

I have installed the tool by simply running:
```
pip install pychd
```
I tried it on Python 3.8 and 3.10, same error on both.

**Comment by diohabara** [comment]
should be working now
